version: '2'

services:

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  userclient-node:
    image: userclient:latest
    ports:
      - "8081:8081"
#    depends_on:
#      - kafka-1
#      - kafka-2
#      - kafka-3
